#!/usr/bin/env python3
"""Generate a narrow, read-only first-pass SQL script for IMES investigations."""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import sys


IDENTIFIER = re.compile(r"^[A-Za-z_#][A-Za-z0-9_$#]*$")


def quote_identifier(value: str) -> str:
    parts = [part.strip() for part in value.split(".")]
    if not 1 <= len(parts) <= 3 or any(not IDENTIFIER.fullmatch(part) for part in parts):
        raise ValueError(
            f"Unsafe SQL identifier {value!r}; use one to three ASCII identifier parts."
        )
    return ".".join(f"[{part}]" for part in parts)


def object_name_literal(value: str) -> str:
    parts = [part.strip() for part in value.split(".")]
    if not 1 <= len(parts) <= 3 or any(not IDENTIFIER.fullmatch(part) for part in parts):
        raise ValueError(f"Unsafe object name {value!r}.")
    return nvarchar_literal(".".join(parts))


def nvarchar_literal(value: str) -> str:
    return "N'" + value.replace("'", "''") + "'"


def build_sql(args: argparse.Namespace) -> str:
    bdjb_table = quote_identifier(args.bdjb_table)
    bill_type_column = quote_identifier(args.bill_type_column)

    lines = [
        "-- Generated by imes-db-development-testing/scripts/generate_first_pass_sql.py",
        "-- Round 1 is intentionally narrow. Evaluate these results before broad searches.",
        "SET NOCOUNT ON;",
        "",
        f"DECLARE @BillType nvarchar(200) = {nvarchar_literal(args.bill_type)};",
    ]

    if args.document_no:
        lines.append(
            f"DECLARE @DocumentNo nvarchar(200) = {nvarchar_literal(args.document_no)};"
        )

    lines.extend(
        [
            "",
            "SELECT DB_NAME() AS CurrentDatabase, @@SERVERNAME AS CurrentServer;",
        ]
    )

    if args.expected_database:
        lines.extend(
            [
                "",
                f"IF DB_NAME() <> {nvarchar_literal(args.expected_database)}",
                "BEGIN",
                "    RAISERROR(N'Connected database does not match the expected target.', 16, 1);",
                "    RETURN;",
                "END;",
            ]
        )

    lines.extend(
        [
            "",
            "-- Exact BDJB entry point.",
            "SELECT *",
            f"FROM {bdjb_table}",
            f"WHERE {bill_type_column} = @BillType;",
            "",
            "-- Narrow metadata for interpreting the returned BDJB rows without guessing columns.",
            "SELECT",
            "    c.column_id,",
            "    c.name AS ColumnName,",
            "    TYPE_NAME(c.user_type_id) AS DataType,",
            "    c.max_length,",
            "    c.is_nullable",
            "FROM sys.columns AS c",
            f"WHERE c.object_id = OBJECT_ID({object_name_literal(args.bdjb_table)})",
            "ORDER BY c.column_id;",
        ]
    )

    if args.document_table:
        document_table = quote_identifier(args.document_table)
        document_column = quote_identifier(args.document_column)
        lines.extend(
            [
                "",
                "-- Exact example document, using the confirmed table and key column.",
                "SELECT *",
                f"FROM {document_table}",
                f"WHERE {document_column} = @DocumentNo;",
            ]
        )
    elif args.document_no:
        lines.extend(
            [
                "",
                "-- Document source is unresolved. Derive its table and key only from the returned",
                "-- BDJB scripts or a confirmed project map, then regenerate with --document-table",
                "-- and --document-column. Do not guess the source table.",
            ]
        )

    return "\n".join(lines) + "\n"


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate the mandatory read-only first round for a BDJB investigation."
    )
    parser.add_argument("--bill-type", required=True, help="Exact BDJB_PJLX value.")
    parser.add_argument("--document-no", help="Exact example document number.")
    parser.add_argument("--expected-database", help="Fail the generated script on a mismatch.")
    parser.add_argument("--bdjb-table", default="dbo.BDJB")
    parser.add_argument("--bill-type-column", default="BDJB_PJLX")
    parser.add_argument("--document-table", help="Confirmed document table.")
    parser.add_argument("--document-column", help="Confirmed document-number column.")
    parser.add_argument("--output", type=Path, help="Write to this file instead of stdout.")
    parser.add_argument(
        "--force", action="store_true", help="Allow replacement of an existing output file."
    )
    args = parser.parse_args(argv)

    if bool(args.document_table) != bool(args.document_column):
        parser.error("--document-table and --document-column must be supplied together.")
    if args.document_table and not args.document_no:
        parser.error("--document-no is required with a document table.")
    return args


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    try:
        sql = build_sql(args)
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    if args.output:
        if args.output.exists() and not args.force:
            print(f"error: output already exists: {args.output}", file=sys.stderr)
            return 2
        if not args.output.parent.exists():
            print(f"error: output directory does not exist: {args.output.parent}", file=sys.stderr)
            return 2
        args.output.write_text(sql, encoding="utf-8", newline="\n")
    else:
        sys.stdout.write(sql)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
